# Generated by Django 5.2.3 on 2025-06-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_accessory_options_accessory_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creater',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
    ]
